window.GD = {

  ROULETTE: [
    { label: '$50K',  amount: 50000   },
    { label: '$100K', amount: 100000  },
    { label: '$100K', amount: 100000  },
    { label: '$100K', amount: 100000  },
    { label: '$100K', amount: 100000  },
    { label: '$200K', amount: 200000  },
    { label: '$200K', amount: 200000  },
    { label: '$200K', amount: 200000  },
    { label: '$350K', amount: 350000  },
    { label: '$350K', amount: 350000  },
    { label: '$500K', amount: 500000  },
    { label: '$750K', amount: 750000  },
    { label: '$1M',   amount: 1000000 },
  ],

  PLAYER_COLORS: [
    { bg:'oklch(68% 0.15 75deg)',  fg:'#080503' },
    { bg:'oklch(60% 0.18 260deg)', fg:'#fff'    },
    { bg:'oklch(60% 0.18 145deg)', fg:'#fff'    },
    { bg:'oklch(58% 0.18 15deg)',  fg:'#fff'    },
    { bg:'oklch(60% 0.18 300deg)', fg:'#fff'    },
    { bg:'oklch(60% 0.18 200deg)', fg:'#fff'    },
  ],

  INVESTMENTS: [
    { id:'stocks',     name:'Bolsa de Valores',   risk:4, minRet:-0.25, maxRet:0.40, volatility:0.18, trend:0.010, color:'oklch(62% 0.18 145deg)', desc:'Alta volatilidad. Grandes ganancias o pérdidas.' },
    { id:'realestate', name:'Bienes Raíces',       risk:2, minRet:-0.05, maxRet:0.20, volatility:0.07, trend:0.015, color:'oklch(65% 0.15 75deg)',  desc:'Estable y predecible. Crecimiento moderado.' },
    { id:'business',   name:'Negocios y Tiendas',  risk:3, minRet:-0.15, maxRet:0.35, volatility:0.14, trend:0.010, color:'oklch(62% 0.18 300deg)', desc:'Alto potencial. Vulnerable a eventos externos.' },
    { id:'bonds',      name:'Bonos del Estado',    risk:1, minRet:0.04,  maxRet:0.09, volatility:0.02, trend:0.005, color:'oklch(62% 0.18 260deg)', desc:'Bajo riesgo. Retorno casi garantizado.' },
    { id:'crypto',     name:'Criptomonedas',       risk:5, minRet:-0.65, maxRet:0.95, volatility:0.38, trend:0.005, color:'oklch(60% 0.18 15deg)',  desc:'Extremadamente volátil. Fortuna o ruina.' },
    { id:'commodities',name:'Materias Primas',     risk:2, minRet:-0.10, maxRet:0.28, volatility:0.11, trend:0.008, color:'oklch(55% 0.12 55deg)',  desc:'Oro, petróleo, recursos naturales.' },
  ],

  // ── MONTHLY MARKET EVENTS ─────────────────────────────────────────────
  MARKET_EVENTS: [
    { id:'stable',        name:'Mes Tranquilo',              severity:'neutral', icon:'check',
      desc:'Los mercados se mantienen estables. Un respiro bienvenido.',
      modifiers:{} },
    { id:'boom',          name:'Boom Económico',             severity:'good',    icon:'trending-up',
      desc:'La economía crece a ritmo récord. Todos los sectores se benefician.',
      modifiers:{ stocks:0.12, realestate:0.08, business:0.10 } },
    { id:'crisis',        name:'Crisis Financiera Global',   severity:'bad',     icon:'alert-triangle',
      desc:'Pánico en los mercados. Los inversores retiran sus fondos.',
      modifiers:{ stocks:-0.15, crypto:-0.20, bonds:0.03 } },
    { id:'crypto_rally',  name:'Rally de Criptomonedas',     severity:'mixed',   icon:'zap',
      desc:'Las criptomonedas explotan. El mercado tradicional se estanca.',
      modifiers:{ crypto:0.40, stocks:-0.05 } },
    { id:'re_bubble',     name:'Boom Inmobiliario',          severity:'good',    icon:'home',
      desc:'Los bienes raíces alcanzan máximos históricos.',
      modifiers:{ realestate:0.22, business:0.05 } },
    { id:'inflation',     name:'Alta Inflación',             severity:'mixed',   icon:'dollar-sign',
      desc:'Los precios suben. Las inversiones conservadoras pierden valor.',
      modifiers:{ bonds:-0.04, commodities:0.15, realestate:0.06 } },
    { id:'oil_crisis',    name:'Crisis del Petróleo',        severity:'mixed',   icon:'layers',
      desc:'El petróleo se dispara. Las materias primas en auge.',
      modifiers:{ commodities:0.25, business:-0.10 } },
    { id:'tech_crash',    name:'Caída Tecnológica',          severity:'bad',     icon:'x',
      desc:'Las empresas tech colapsan. Cripto y bolsa se hunden.',
      modifiers:{ stocks:-0.22, crypto:-0.35 } },
    { id:'gold_rush',     name:'Fiebre del Oro',             severity:'mixed',   icon:'star',
      desc:'Los inversores huyen a activos refugio. El oro brilla.',
      modifiers:{ commodities:0.28, stocks:-0.08 } },
    { id:'recession',     name:'Recesión Económica',         severity:'bad',     icon:'alert-triangle',
      desc:'La economía se contrae. Solo los preparados sobreviven.',
      modifiers:{ stocks:-0.18, business:-0.15, realestate:-0.08, bonds:0.05 } },
    { id:'low_rates',     name:'Tasas de Interés Bajas',     severity:'good',    icon:'trending-up',
      desc:'El banco central baja tasas. El dinero fluye a los mercados.',
      modifiers:{ stocks:0.08, realestate:0.10, bonds:-0.02 } },
    { id:'trade_war',     name:'Guerra Comercial',           severity:'bad',     icon:'alert-triangle',
      desc:'Tensiones internacionales golpean el comercio global.',
      modifiers:{ stocks:-0.10, commodities:0.12, business:-0.12 } },
  ],

  // ── MARKET NEWS (pistas antes de invertir) ──────────────────────────────
  // accurate: true = la pista coincide con el evento real
  MARKET_NEWS: [
    { text:'"La economía muestra señales de recuperación sólida."',      target:'stocks',     accurate:true  },
    { text:'"Analistas advierten sobre corrección en criptomonedas."',   target:'crypto',     accurate:true  },
    { text:'"El sector inmobiliario muestra señales de enfriamiento."',  target:'realestate', accurate:false },
    { text:'"Los bonos del estado gozan de gran demanda inversora."',    target:'bonds',      accurate:true  },
    { text:'"El precio del petróleo sube por tensiones geopolíticas."',  target:'commodities',accurate:true  },
    { text:'"Los negocios locales reportan ventas récord este mes."',    target:'business',   accurate:true  },
    { text:'"Rumores de una nueva regulación cripto generan nerviosismo."',target:'crypto',   accurate:false },
    { text:'"Grandes fondos aumentan posición en bienes raíces."',      target:'realestate', accurate:true  },
    { text:'"La inflación presiona al alza las materias primas."',      target:'commodities',accurate:true  },
    { text:'"Los mercados bursátiles registran máximos históricos."',   target:'stocks',     accurate:false },
    { text:'"Inversores huyen de renta variable hacia bonos seguros."', target:'bonds',      accurate:false },
    { text:'"Las tiendas físicas pierden cuota frente al comercio digital."',target:'business',accurate:false},
  ],

  // ── PROPIEDADES EN SUBASTA ────────────────────────────────────────────
  AUCTION_PROPERTIES: [
    { id:'ap1', name:'Apartamento Centro',    value:120000, monthlyRent:3200,  type:'property', rarity:'común'      },
    { id:'ap2', name:'Villa Las Palmas',      value:280000, monthlyRent:7000,  type:'property', rarity:'infrecuente' },
    { id:'ap3', name:'Local Comercial Sur',   value:95000,  monthlyRent:2600,  type:'property', rarity:'común'      },
    { id:'ap4', name:'Penthouse Torre Dorada',value:420000, monthlyRent:11000, type:'property', rarity:'rara'        },
    { id:'ap5', name:'Casa Quinta Azul',      value:190000, monthlyRent:4800,  type:'property', rarity:'infrecuente' },
    { id:'ap6', name:'Oficinas Plaza Mayor',  value:310000, monthlyRent:8200,  type:'property', rarity:'infrecuente' },
    { id:'ap7', name:'Bodega Industrial Norte',value:150000,monthlyRent:3800,  type:'property', rarity:'común'      },
    { id:'ap8', name:'Suite Hotel Mirador',   value:230000, monthlyRent:6400,  type:'property', rarity:'infrecuente' },
    { id:'ap9', name:'Terreno Río Grande',    value:80000,  monthlyRent:1200,  type:'property', rarity:'común'      },
    { id:'ap10',name:'Residencia El Encanto', value:360000, monthlyRent:9200,  type:'property', rarity:'rara'        },
  ],

  ARTIFACTS: [
    { id:'golden_hand',    name:'La Mano Dorada',          type:'blessing', rarity:'rara',
      flavor:'Una mano de oro macizo. Todo lo que toca se convierte en riqueza.',
      desc:'Tus inversiones rinden el doble este mes.',
      effect:'investment_multiplier', value:2.0, duration:1 },
    { id:'fortune_stone',  name:'Piedra de la Fortuna',    type:'blessing', rarity:'común',
      flavor:'Una piedra pulida que vibra suavemente con energía dorada.',
      desc:'Ganas $75,000 en efectivo de inmediato.',
      effect:'cash_bonus', value:75000 },
    { id:'lost_deed',      name:'La Escritura Perdida',    type:'blessing', rarity:'infrecuente',
      flavor:'Antiguo documento con sellos de oro. La propiedad ya es tuya.',
      desc:'Recibes una propiedad gratis valuada en $200,000.',
      effect:'free_property', value:200000 },
    { id:'market_oracle',  name:'Oráculo del Mercado',     type:'blessing', rarity:'rara',
      flavor:'Una bola de cristal que revela el futuro del mercado.',
      desc:'Ves los resultados del próximo mes antes de invertir.',
      effect:'oracle', duration:1 },
    { id:'prosperity',     name:'Amuleto de Prosperidad',  type:'blessing', rarity:'infrecuente',
      flavor:'Joya ancestral que irradia abundancia.',
      desc:'+50% a todos tus retornos de inversión por 2 meses.',
      effect:'investment_multiplier', value:1.5, duration:2 },
    { id:'jade_clover',    name:'Trébol de Jade',          type:'blessing', rarity:'infrecuente',
      flavor:'Cuatro hojas perfectas en jade.',
      desc:'Ganas entre $20,000 y $250,000 al azar.',
      effect:'random_cash', minVal:20000, maxVal:250000 },
    { id:'sultans_crown',  name:'Corona del Sultán',       type:'blessing', rarity:'rara',
      flavor:'El sultán que la portaba poseía todo el reino.',
      desc:'+$15,000 por cada propiedad tuya, durante 3 meses.',
      effect:'property_income_boost', value:15000, duration:3 },
    { id:'scroll_thief',   name:'Pergamino del Ladrón',    type:'blessing', rarity:'infrecuente',
      flavor:'Instrucciones muy detalladas para el robo perfecto.',
      desc:'Robas $80,000 de efectivo a un jugador al azar.',
      effect:'steal_cash', value:80000 },
    { id:'golden_bell',    name:'La Campana de Oro',       type:'blessing', rarity:'rara',
      flavor:'Su tañido ahuyenta todo mal.',
      desc:'Eres inmune a todas las maldiciones durante 2 meses.',
      effect:'curse_immunity', duration:2 },
    { id:'abundance',      name:'Cristal de la Abundancia',type:'blessing', rarity:'infrecuente',
      flavor:'Amplifica todo lo que tocas.',
      desc:'El valor de todas tus propiedades se duplica este mes.',
      effect:'property_double', duration:1 },
    { id:'evil_eye',       name:'El Ojo Maldito',          type:'curse', rarity:'común',
      flavor:'El ojo te observó. Tus inversiones comenzaron a marchitar.',
      desc:'Pierdes el 25% del valor de todas tus inversiones.',
      effect:'investment_loss', value:0.25 },
    { id:'ghost_fire',     name:'Fuego Fatuo',             type:'curse', rarity:'infrecuente',
      flavor:'Llamas azules que no queman madera, sino fortunas.',
      desc:'Una propiedad aleatoria se incendia. La pierdes para siempre.',
      effect:'destroy_property' },
    { id:'phantom_debt',   name:'Deuda Fantasma',          type:'curse', rarity:'infrecuente',
      flavor:'Una deuda que nadie recuerda contratar. El cobrador sí.',
      desc:'Adquieres una deuda de $150,000 al 20% de interés.',
      effect:'add_debt', value:150000, rate:0.20 },
    { id:'market_shadow',  name:'Sombra del Mercado',      type:'curse', rarity:'común',
      flavor:'Una sombra cae sobre tus finanzas.',
      desc:'Ninguna de tus inversiones genera retorno este mes.',
      effect:'zero_returns', duration:1 },
    { id:'greed_hand',     name:'La Mano Ávara',           type:'curse', rarity:'infrecuente',
      flavor:'No puedes resistirte.',
      desc:'Debes invertir todo tu efectivo el próximo mes.',
      effect:'forced_invest', duration:1 },
    { id:'cursed_contract',name:'El Contrato Maldito',     type:'curse', rarity:'común',
      flavor:'Lo firmaste sin leer. Siempre hay letra pequeña.',
      desc:'Pierdes el 30% de tu efectivo de inmediato.',
      effect:'cash_loss', value:0.30 },
    { id:'rat_plague',     name:'Plaga de Ratas',          type:'curse', rarity:'común',
      flavor:'Llegaron al almacén primero.',
      desc:'Todos tus negocios generan cero este mes.',
      effect:'business_zero', duration:1 },
    { id:'pandoras_box',   name:'Caja de Pandora',         type:'curse', rarity:'infrecuente',
      flavor:'Estaba cerrada por una razón.',
      desc:'Pierdes $30,000 cada mes durante los próximos 3 meses.',
      effect:'monthly_drain', value:30000, duration:3 },
    { id:'moon_curse',     name:'Maldición de la Luna',    type:'curse', rarity:'rara',
      flavor:'La luna llena vio algo que no debía.',
      desc:'Catástrofe: −40% efectivo, propiedad perdida, o $250K en deuda.',
      effect:'random_catastrophe' },
    { id:'shadow_stolen',  name:'El Ladrón de Sombras',    type:'curse', rarity:'infrecuente',
      flavor:'Ni siquiera viste quién fue.',
      desc:'Un jugador al azar te roba $60,000 en efectivo.',
      effect:'stolen_cash', value:60000 },
  ],

  LENDER: {
    name: 'Don Aurelio',
    title: 'El Prestamista',
    rates: [
      { months:3,  rate:0.10, label:'Corto plazo — 3 meses'  },
      { months:6,  rate:0.15, label:'Mediano plazo — 6 meses' },
      { months:12, rate:0.25, label:'Largo plazo — 12 meses' },
    ],
    amounts: [50000, 100000, 200000, 500000],
    // Context-aware greetings based on player state
    greetByState: {
      rich:       ['¿Ves? Ya no necesitas mi ayuda. Qué... buenas noticias.','Todo va bien para ti. Por ahora.'],
      normal:     ['¿Así que necesitas un poco de ayuda? No hay problema... para mis amigos.','El dinero es como el agua. Siempre encuentro por dónde fluir.'],
      struggling: ['Veo que el destino no ha sido amable contigo. Quizás yo sí pueda serlo.','Siéntate. El dinero nunca es un problema... cuando yo soy tu solución.'],
      bankrupt:   ['Qué situación más... delicada. Tengo una propuesta que no puedes rechazar.','Los que caen más bajo suelen necesitar más ayuda. Soy generoso con los desesperados.'],
      hasLoans:   ['¿Más dinero? Claro. La deuda anterior... ya la contabilizaré.','"Mi amigo de siempre". Eso me gusta. Los intereses también me gustan.'],
    },
    warnings: [
      'Los intereses no esperan. Ni yo, amigo.',
      'Confío en ti. Sería una lástima que esa confianza se rompiera.',
      'Mis términos son flexibles. Pero mi paciencia, no tanto.',
      'El dinero prestado siempre regresa. Siempre.',
    ],
    collection: [
      '¿Cómo van esos pagos? Pregunto por curiosidad.',
      'Tu propiedad luce muy interesante. Muy interesante.',
      'Los accidentes pasan, especialmente con deudas pendientes.',
      'Mis amigos dicen que eres un buen pagador. No los decepciones.',
    ],
  },

  PROPERTY_NAMES: [
    'Apartamento Centro Histórico','Villa Las Palmas','Local Comercial Sur',
    'Penthouse Torre Dorada','Casa Quinta Azul','Oficinas Plaza Mayor',
    'Bodega Industrial Norte','Residencia El Encanto','Suite Hotel Mirador',
    'Terreno Río Grande',
  ],
};
